spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer-uri}
          jwk-set-uri: ${issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: ${resource-id}
      principle-attribute: ${principle-attribute}
